import React from 'react';
import { Link } from 'react-router-dom';
import { useWallet } from '../context/WalletContext';
import { Button, Card } from '../components/UI';
<<<<<<< HEAD
import { Database, Shield, Zap, Globe, ArrowRight } from 'lucide-react';
=======
import { Database, Shield, Zap, Globe, ShoppingBag, Package, ArrowRight, UploadCloud, Cpu, CheckCircle, Lock, Image, Video, FileText, Music } from 'lucide-react';
>>>>>>> 0a9abf9d888ec340e28ff1cdc8734f70d46661d9

const Home = () => {
  const { isConnected } = useWallet();

  return (
    <div className="min-h-screen bg-gradient-to-b from-white to-gray-50">
      {/* Hero Section */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="text-center">
          <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-6">
            AI-Powered<br />
            <span className="text-primary-600">Synthetic Data Generation</span>
          </h1>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto mb-8">
<<<<<<< HEAD
            Request custom synthetic datasets generated by AI models with built-in quality verification,
            blockchain transparency, and IPFS-backed reporting.
=======
            Generate high-quality synthetic datasets (image, video, text, audio),
            automatically verify them by comparing to submitted real data, and
            publish an immutable QA correlation report stored on-chain and on IPFS —
            providing tamper-proof proof suitable for sensitive domains like medical research.
>>>>>>> 0a9abf9d888ec340e28ff1cdc8734f70d46661d9
          </p>
          
          <div className="flex items-center justify-center gap-4">
            {isConnected ? (
              <Link to="/dashboard">
                <Button size="lg">
                  <Database className="h-5 w-5 mr-2" />
                  Go to Dashboard
                </Button>
              </Link>
            ) : (
              <Button size="lg">
                Connect Wallet to Get Started
              </Button>
            )}
          </div>
        </div>
      </div>

      {/* Features */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <h2 className="text-3xl font-bold text-center text-gray-900 mb-12">
          How It Works
        </h2>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          <FeatureCard
<<<<<<< HEAD
            icon={<Database className="h-8 w-8" />}
            title="Request Data"
            description="Specify your requirements and optionally provide sample data"
          />
          <FeatureCard
            icon={<Zap className="h-8 w-8" />}
            title="AI Generation"
            description="AI models generate your custom dataset instantly"
          />
          <FeatureCard
            icon={<Shield className="h-8 w-8" />}
            title="Quality Check"
            description="Automated verification with reports stored on IPFS"
          />
          <FeatureCard
            icon={<Globe className="h-8 w-8" />}
            title="View Results"
            description="Access dataset and transparent QA reports"
=======
            icon={<UploadCloud className="h-8 w-8" />}
            title="Upload Real Data"
            description="Buyers upload sample data that defines the request (image, video, text, audio)"
          />
          <FeatureCard
            icon={<Cpu className="h-8 w-8" />}
            title="Generate Synthetic"
            description="AI models generate synthetic datasets tailored to the request"
          />
          <FeatureCard
            icon={<CheckCircle className="h-8 w-8" />}
            title="Verify & QA"
            description="Automated correlation analysis produces a JSON QA report comparing real vs synthetic"
          />
          <FeatureCard
            icon={<Lock className="h-8 w-8" />}
            title="Immutable Proof"
            description="QA reports and proofs are stored on IPFS and recorded on-chain for tamper-proof audits"
>>>>>>> 0a9abf9d888ec340e28ff1cdc8734f70d46661d9
          />
        </div>
      </div>

      {/* Benefits */}
      <div className="bg-white py-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
            <div>
              <h2 className="text-3xl font-bold text-gray-900 mb-6">
                Why Synthetic Data?
              </h2>
              <ul className="space-y-4">
<<<<<<< HEAD
                <BenefitItem text="Instant AI-powered dataset generation" />
                <BenefitItem text="Automated quality verification" />
                <BenefitItem text="Blockchain-backed transparency" />
                <BenefitItem text="IPFS quality reports" />
                <BenefitItem text="Support for multiple data formats" />
=======
                <BenefitItem text="Decentralized marketplace with no intermediaries" />
                <BenefitItem text="Automatic correlation-based QA: we compare real and synthetic samples and emit a detailed JSON report" />
                <BenefitItem text="QA reports are stored on IPFS and anchored on-chain so results cannot be tampered with" />
                <BenefitItem text="Smart contract escrow protection for fair payment and dispute resolution" />
                <BenefitItem text="Supports Image, Video, Textual, and Audio datasets — designed for regulated domains like healthcare" />
>>>>>>> 0a9abf9d888ec340e28ff1cdc8734f70d46661d9
              </ul>
            </div>
            
            <div className="grid grid-cols-2 gap-4">
<<<<<<< HEAD
              <StatCard label="Requests" value="1,234" />
              <StatCard label="Datasets" value="5,678" />
              <StatCard label="Avg Score" value="92/100" />
              <StatCard label="Users" value="456" />
=======
              <StatCard label="Datasets Sold" value="0" />
                <StatCard label="Active Sellers" value="0" />
                <StatCard label="Total Volume" value="0 ETH" />
                <StatCard label="Avg QA Score" value="0/100" />
>>>>>>> 0a9abf9d888ec340e28ff1cdc8734f70d46661d9
            </div>
          </div>
        </div>
      </div>

      {/* Formats supported */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <h3 className="text-2xl font-semibold text-center mb-6">Formats we support</h3>
        <div className="flex items-center justify-center gap-8">
          <div className="flex flex-col items-center">
            <Image className="h-8 w-8 text-primary-600 mb-2" />
            <span className="text-sm">Image</span>
          </div>
          <div className="flex flex-col items-center">
            <Video className="h-8 w-8 text-primary-600 mb-2" />
            <span className="text-sm">Video</span>
          </div>
          <div className="flex flex-col items-center">
            <FileText className="h-8 w-8 text-primary-600 mb-2" />
            <span className="text-sm">Text</span>
          </div>
          <div className="flex flex-col items-center">
            <Music className="h-8 w-8 text-primary-600 mb-2" />
            <span className="text-sm">Audio</span>
          </div>
        </div>
      </div>

      {/* CTA */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <Card className="p-12 text-center bg-gradient-to-r from-primary-50 to-primary-100 border-primary-200">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">
            Ready to get started?
          </h2>
          <p className="text-gray-600 mb-8 text-lg">
            Connect your wallet and start generating synthetic datasets today
          </p>
          {!isConnected && (
            <Button size="lg">
              Connect Wallet
              <ArrowRight className="h-5 w-5 ml-2" />
            </Button>
          )}
        </Card>
      </div>
    </div>
  );
};

const FeatureCard = ({ icon, title, description }) => {
  return (
    <Card className="p-6 text-center hover:shadow-lg transition-shadow">
      <div className="inline-flex items-center justify-center w-16 h-16 bg-primary-100 text-primary-600 rounded-full mb-4">
        {icon}
      </div>
      <h3 className="text-lg font-semibold text-gray-900 mb-2">{title}</h3>
      <p className="text-gray-600 text-sm">{description}</p>
    </Card>
  );
};

const BenefitItem = ({ text }) => {
  return (
    <li className="flex items-start">
      <svg className="h-6 w-6 text-green-500 mr-2 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
      </svg>
      <span className="text-gray-700">{text}</span>
    </li>
  );
};

const StatCard = ({ label, value }) => {
  return (
    <Card className="p-6">
      <p className="text-sm text-gray-600 mb-1">{label}</p>
      <p className="text-2xl font-bold text-primary-600">{value}</p>
    </Card>
  );
};

export default Home;